[mqtt]

# ID used when connecting MQTT client, needs to be unique across MQTT clients connected to the broker
id = "hue-mqtt"

# Domain name / IP address and port of the MQTT broker
host = "mosquitto"
port = 1883

# MQTT topic where sensor updates will be published
sensor_topic = "home/sensors/hue/{id}"

# MQTT topic where light updates will be published
light_topic = "home/lights/hue/{id}"

# MQTT topic where if another client publishes a light update, we will send the
# received light state to the Hue bridge
light_topic_set = "home/lights/hue/{id}/set"

[hue_bridge]

# Domain name / IP address of the Hue bridge
addr = "192.168.2.40"

# App key or "username" for authenticating to the Hue bridge
appkey = "0123456789abcdef0123456789abcdef0123456-"

# See https://github.com/FruitieX/hue-mqtt#quick-start
# If you have trouble connecting, try running
# `openssl s_client -showcerts -connect ip_of_your_hue_bridge:443`
# and replace the self signed certificate below with the certificate that can be
# found in the output of that command.

# self_signed_cert = """
# -----BEGIN CERTIFICATE-----
# ...
# -----END CERTIFICATE-----
# """

# Disable checks for hostname in Hue bridge certificate. You need to disable this unless the Hue bridge's hostname resolves to its IP address.
disable_host_name_verification = true